/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface BankForm {}
  interface DashBoardDisplay {}
  interface ImageCard {
    'description': string;
    'heading': string;
    'prince': number;
    'src': string;
    'subHeading': string;
  }
  interface UpLoadForm {}
  interface VideoPlayer {}
}

declare global {


  interface HTMLBankFormElement extends Components.BankForm, HTMLStencilElement {}
  var HTMLBankFormElement: {
    prototype: HTMLBankFormElement;
    new (): HTMLBankFormElement;
  };

  interface HTMLDashBoardDisplayElement extends Components.DashBoardDisplay, HTMLStencilElement {}
  var HTMLDashBoardDisplayElement: {
    prototype: HTMLDashBoardDisplayElement;
    new (): HTMLDashBoardDisplayElement;
  };

  interface HTMLImageCardElement extends Components.ImageCard, HTMLStencilElement {}
  var HTMLImageCardElement: {
    prototype: HTMLImageCardElement;
    new (): HTMLImageCardElement;
  };

  interface HTMLUpLoadFormElement extends Components.UpLoadForm, HTMLStencilElement {}
  var HTMLUpLoadFormElement: {
    prototype: HTMLUpLoadFormElement;
    new (): HTMLUpLoadFormElement;
  };

  interface HTMLVideoPlayerElement extends Components.VideoPlayer, HTMLStencilElement {}
  var HTMLVideoPlayerElement: {
    prototype: HTMLVideoPlayerElement;
    new (): HTMLVideoPlayerElement;
  };
  interface HTMLElementTagNameMap {
    'bank-form': HTMLBankFormElement;
    'dash-board-display': HTMLDashBoardDisplayElement;
    'image-card': HTMLImageCardElement;
    'up-load-form': HTMLUpLoadFormElement;
    'video-player': HTMLVideoPlayerElement;
  }
}

declare namespace LocalJSX {
  interface BankForm extends JSXBase.HTMLAttributes<HTMLBankFormElement> {}
  interface DashBoardDisplay extends JSXBase.HTMLAttributes<HTMLDashBoardDisplayElement> {}
  interface ImageCard extends JSXBase.HTMLAttributes<HTMLImageCardElement> {
    'description'?: string;
    'heading'?: string;
    'prince'?: number;
    'src'?: string;
    'subHeading'?: string;
  }
  interface UpLoadForm extends JSXBase.HTMLAttributes<HTMLUpLoadFormElement> {}
  interface VideoPlayer extends JSXBase.HTMLAttributes<HTMLVideoPlayerElement> {}

  interface IntrinsicElements {
    'bank-form': BankForm;
    'dash-board-display': DashBoardDisplay;
    'image-card': ImageCard;
    'up-load-form': UpLoadForm;
    'video-player': VideoPlayer;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


